name: Release mosdns

on:
  push:
    paths-ignore:
      - ".gitignore"
      - ".gitattributes"
      - "LICENSE"
      - "README.md"
      - '.github/**'
    tags:
      - 'v*'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env: 
    TZ: Asia/Hong_Kong

jobs:

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow runs delete
        uses: InfraWay/delete-workflow-runs@v2.1.2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Test
        run: go test -race -v ./...

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build
        run: python ./release.py
        env:
          CGO_ENABLED: '0'

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: './release/mosdns*.zip'
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
